version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:2019'
    ports:
      - '80:80'
      - '7098:80'
      - '7097:443'
    volumes:
      - 'phabricator_data:/bitnami'
      - './vhost.conf:/opt/bitnami/apache/conf/vhosts/vhost.conf'
    depends_on:
      - mariadb
  web-nginx-aiapp-server:
    image: nginx:1.11.6-alpine
    restart: always
    ports:
      - "7096:7098"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
